apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: alloy-instrumentation
spec:
  exporter:
    endpoint: http://alloy:4318
  env:
    - name: OTEL_EXPORTER_OTLP_HEADERS
      value: 'Authorization=Basic x'
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: parentbased_traceidratio
    argument: '1.0'
  python:
    env:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://alloy:4318
  dotnet:
    env:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://alloy:4318
  java:
    env:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://alloy:4317
  nodejs:
    env:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://alloy:4317
