apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
  labels:
    app: petclinic
spec:
  selector:
    matchLabels:
      app: petclinic
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: petclinic
      annotations:
        instrumentation.opentelemetry.io/inject-java: "true"
        resource.opentelemetry.io/service.name: "petclinic-java"
        resource.opentelemetry.io/service.namespace: "game"
        resource.opentelemetry.io/service.version: "1.2.3"
        resource.opentelemetry.io/deployment.environment.name: "production"
    spec:
      containers:
      - name: petclinic
        image: springio/petclinic:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: petclinic
  labels:
    app: petclinic
spec:
  type: ClusterIP
  selector:
    app: petclinic
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
